
# installation path
ifndef INSTALL_PATH
INSTALL_PATH = /usr/local/lib/lv2
endif
INSTALLATION_PATH = $(DESTDIR)$(INSTALL_PATH)

all:

clean:

install:
	install -d $(INSTALLATION_PATH)
	cp -r *.modgui $(INSTALLATION_PATH)
